---

# Copyright 2019 – 2020 David Kent Consulting, Inc.
# All Rights Reserved.
# 
# NOTICE:  All information contained herein is, and remains
# the property of David Kent Consulting, Inc.; David Kent Cloud Solutions, Inc.;
# and its affiliates (The Company). The intellectual and technical concepts contained
# herein are proprietary to The Company and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from The Company.
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

- name: Updates Security List Rules within the ERP tenant
  gather_facts: no
  hosts: localhost
  vars:
    Automation:
      compartment:  "auto_comp"
      vcn_name:     "auto_vcn"
      sec_name:     "'Default Security List for auto_vcn'"
    Bastion:
      compartment:  "bas_comp"
      vcn_name:     "bas_vcn"
      sec_name:     "'Default Security List for bas_vcn'"
    Database:
      compartment:  "dbs_comp"
      vcn_name:     "dbs_vcn"
      sec_name:     "'Default Security List for dbs_vcn'"
    Test:
      compartment:  "tst_comp"
      vcn_name:     "tst_vcn"
      sec_name:     "'Default Security List for tst_vcn'"
    Vpn:
      compartment:  "vpn_comp"
      vcn_name:     "vpn_vcn"
      sec_name:     "'Default Security List for vpn_vcn'"      
    Web:
      compartment:  "web_comp"
      vcn_name:     "web_vcn"
      sec_name:     "'Default Security List for web_vcn'"

  tasks:

#####################################################################################################
###                               Automation Compartment                                          ###
#####################################################################################################
  - include_tasks: 019_PopulateSecurityInboundTcpListWithPurge.yaml
    vars:
      VcnProperties:      "{{ Automation }}"
      rule:
        source:             "0.0.0.0/0"
        protocol:           "6"
        min_port_range: "22"
        max_port_range: "22"

  - include_tasks: 019_PopulateSecurityOutboundTcpListWithPurge.yaml
    vars:
      VcnProperties:      "{{ Automation }}"
      rule:
        destination:        "0.0.0.0/0"
        protocol:           "6"
        min_port_range: "1"
        max_port_range: "65535"
#####################################################################################################
###                               Bastion Compartment                                             ###
#####################################################################################################
  - include_tasks: 019_PopulateSecurityInboundTcpListWithPurge.yaml
    vars:
      VcnProperties:      "{{ Bastion }}"
      rule:
        source:             "0.0.0.0/0"
        protocol:           "6"
        min_port_range: "22"
        max_port_range: "22"

  - include_tasks: 019_PopulateSecurityOutboundTcpListWithPurge.yaml
    vars:
      VcnProperties:      "{{ Bastion }}"
      rule:
        destination:        "0.0.0.0/0"
        protocol:           "6"
        min_port_range: "1"
        max_port_range: "65535"

#####################################################################################################
###                               Database Compartment                                            ###
#####################################################################################################
  - include_tasks: 019_PopulateSecurityInboundTcpListWithPurge.yaml
    vars:
      VcnProperties:      "{{ Database }}"
      rule:
        source:             "0.0.0.0/0"
        protocol:           "6"
        min_port_range: "22"
        max_port_range: "22"

  - include_tasks: 019_PopulateSecurityInboundIcmpListNoPurge.yaml
    vars:
      VcnProperties:      "{{ Database }}"
      rule:
        source:             "10.0.0.0/8"
        protocol:           "1"

  - include_tasks: 019_PopulateSecurityInboundTcpListNoPurge.yaml
    vars:
      VcnProperties:      "{{ Database }}"
      rule:
        source:             "10.0.0.0/8"
        protocol:           "6"
        min_port_range: "1"
        max_port_range: "65535"

  - include_tasks: 019_PopulateSecurityInboundUdpListNoPurge.yaml
    vars:
      VcnProperties:      "{{ Database }}"
      rule:
        source:             "10.0.0.0/8"
        protocol:           "17"
        min_port_range: "1"
        max_port_range: "65535"

  - include_tasks: 019_PopulateSecurityOutboundTcpListWithPurge.yaml
    vars:
      VcnProperties:      "{{ Database }}"
      rule:
        destination:        "10.0.0.0/8"
        protocol:           "6"
        min_port_range: "1"
        max_port_range: "65535"

  - include_tasks: 019_PopulateSecurityOutboundIcmpListNoPurge.yaml
    vars:
      VcnProperties:      "{{ Database }}"
      rule:
        destination:      "10.0.0.0/8"
        protocol:         "1"        

  - include_tasks: 019_PopulateSecurityOutboundTcpListNoPurge.yaml
    vars:
      VcnProperties:      "{{ Database }}"
      rule:
        destination:        "0.0.0.0/0"
        protocol:           "6"
        min_port_range: "22"
        max_port_range: "22"

  - include_tasks: 019_PopulateSecurityOutboundTcpListNoPurge.yaml
    vars:
      VcnProperties:      "{{ Database }}"
      rule:
        destination:        "0.0.0.0/0"
        protocol:           "6"
        min_port_range: "443"
        max_port_range: "443"

  - include_tasks: 019_PopulateSecurityOutboundUdpListNoPurge.yaml
    vars:
      VcnProperties:      "{{ Database }}"
      rule:
        destination:        "10.0.0.0/8"
        protocol:           "17"
        min_port_range: "1"
        max_port_range: "65535"
