---
# Copyright 2019 – 2020 David Kent Consulting, Inc.
# All Rights Reserved.
# 
# NOTICE:  All information contained herein is, and remains
# the property of David Kent Consulting, Inc.; David Kent Cloud Solutions, Inc.;
# and its affiliates (The Company). The intellectual and technical concepts contained
# herein are proprietary to The Company and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from The Company.
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

- name: Create File Systems in OCI Tenant
  gather_facts: no
  hosts: localhost
  vars:
    python_path:                    "/Users/henrywojteczko/bin/python"
    DKCUFS01:
      availability_domain:          "clNq:US-ASHBURN-AD-1"
      display_name:                 "DKCUFS01"
      mt_display_name:              "DKCUFS01_MT"
      hostname_label:               "DKCUFS01"
      ip_address:                   "10.20.0.3"
    DKCUFS02:
      availability_domain:          "clNq:US-ASHBURN-AD-2"
      display_name:                 "DKCUFS02"
      mt_display_name:              "DKCUFS02_MT"
      hostname_label:               "DKCUFS02"
      ip_address:                   "10.20.0.4"

      

# Compartment and VCN data
    Database:
      compartment:                  "dbs_comp"
      vcn_name:                     "dbs_vcn"
      subnet_name:                  "dbs_sub"

    # All vars required to create this VM
    # This VM to be created in the bastion compartment. It will have a publically visible IP address.
    # The security list is to be used to restrict access to the VM as needed, such as blocking internet
    # access.

  tasks:
    - include_tasks: 300_CreateFILESYSTEM.yaml
      vars:
        FileSystem:                       "{{ DKCUFS01 }}"
        VcnProperties:                    "{{ Database }}"

    - include_tasks: 300_CreateFILESYSTEM.yaml
      vars:
        FileSystem:                       "{{ DKCUFS02 }}"
        VcnProperties:                    "{{ Database }}"
