# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release_03222022

pool:
  vmImage: ubuntu-latest

stages:
  - stage: TerraformValidateStage
    jobs:
      - job: TerraformValidateJob
        continueOnError: false
        steps:
        
        - task: PublishPipelineArtifact@1
          displayName: Publish the Artifacts
          inputs:
            targetPath: '$(Pipeline.Workspace)'
            artifact: 'Publish the Artifacts'
            publishLocation: 'pipeline'
        
        - task: Bash@3
          displayName: List the artifacts parent directory
          inputs:
            targetType: 'inline'
            script: '/bin/ls'
          
