---
# Copyright 2019 – 2020 David Kent Consulting, Inc.
# All Rights Reserved.
# 
# NOTICE:  All information contained herein is, and remains
# the property of David Kent Consulting, Inc.; David Kent Cloud Solutions, Inc.;
# and its affiliates (The Company). The intellectual and technical concepts contained
# herein are proprietary to The Company and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from The Company.
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

- name: Create VMs in  MESSIAH OCI Tenant
  gather_facts: no
  hosts: localhost
  vars:
    # All vars required to create this VM
    # This VM to be created in the bastion compartment. It will have a publically visible IP address.
    # The security list is to be used to restrict access to the VM as needed, such as blocking internet
    # access.

#     ssh_authorized_keys:       "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDPuBXnBWAPj+nmZkfoMSXsiPYmVRhlbfVHLd80fRrhxL1CExHQKIIG/9B2s/np2i1eRY41Ail4tiinyymfZRO5oU264akRqTocw3/IHD9oB9DehBMiEyUPeUcHqAvlfmgFDBHaIlTPswcd7eYQx4jfQfIRDiz2NDJtLCBtDGzEaoou7Vy/i9AG7ALrglAkP5gWfcgNw2UhEYj1eoSIJDgolU9PODTNqCuuD0twM1LJJ9c84JPBle5Nfu6i8UdbDIsjTNSDPJ0RbXj6FuUQ4vlpGyIfWjExJn5pzBcgH8gAsg0Wja9gVyGG/s64SqOI2y4KoQ9drmBXR7EtPkEpjWh"
     ssh_authorized_keys:       "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAiF79KSjFcPpRJzHPQB18f5QdRWvV3ZH15hAEdbd5BklUnFNRmr1kKGf9/Ia1dhcfNA5QGsNUDDYY1KZdN42XDGeziSZkgkfAhCN5BOr3zD6LDQhcA/hMnkO1g6iF1R18GbTuCYLGY6dkjho6dinSFTy9aGxEvJdWuAIibTUY+Yz3kyQYoKk2GGVqry54sojVvwkPYtpLtyxYxE0vF/Q0Pfg1YGEYyi2mIHXf5fSweYCuu8mHyVlMCX3WJz8r1YDOgb4my2zZBS34GzlN6boGdvjjewdBfDUUd2buBPcjMGLp/FZlG3xTReg36GrLdsC/h3mhHjnSX+SS+xYuCUlFVw=="
     LinuxGoldenImage:           "ocid1.image.oc1.iad.aaaaaaaaenjzm42tmnhyirtbclrhdoqej4gprk57glcmw7x7t3oup25jjcvq"
     LinuxGoldenImagev2:         "ocid1.image.oc1.iad.aaaaaaaakqdwhxgsb7ucoaid6okz2r6loofqwqok7jvmdaok6il2mszbucgq"
     W2019_GoldenImage:          "ocid1.image.oc1.iad.aaaaaaaaqizdzsuugkasapickbey6cyk2vtgjpg3aeotkgr4fug2zcru7l4q"

  tasks:

# VM MESBASP01
#     - name: Get Compartment Data 
#       command: "pwsh GetActiveChildCompartmentID.ps1 bastion"
#       register: BastionCompartmentId

#     - name: Get Subnet Data
#       command: "pwsh GetSubnetID.ps1 bastion bastion_vcn bastion_subnet"
#       register: BastionSubnetId

#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "mesbasp01"
#        compartment_id:         "{{ BastionCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ BastionSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard.E2.1"
#        availability_domain:    "vSHs:US-ASHBURN-AD-3"
#        assign_public_ip:       true
#        private_ip:             '10.40.255.2'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ LinuxGoldenImage }}"

#     - name: Print Instance source_details
#       debug:
#        msg: "Launch instance completed for MESBASP01"

# VM MESRMANP01
#     - name: Get Compartment Data 
#       command: "pwsh GetActiveChildCompartmentID.ps1 database"
#       register: DatabaseCompartmentId

#     - name: Get Subnet Data
#       command: "pwsh GetSubnetID.ps1 database database_vcn database_subnet"
#       register: DatabaseSubnetId

#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "mesrmanp01"
#        compartment_id:         "{{ DatabaseCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ DatabaseSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard.E2.8"
#        availability_domain:    "vSHs:US-ASHBURN-AD-3"
#        assign_public_ip:       false
#        private_ip:             '10.40.0.2'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ LinuxGoldenImage }}"

#     - name: Print Instance source_details
#       debug:
#        msg: "Launch instance completed for test03"

# VM MESRMANP01
     - name: Get Compartment Data 
       command: "pwsh GetActiveChildCompartmentID.ps1 database"
       register: DatabaseCompartmentId

     - name: Get Subnet Data
       command: "pwsh GetSubnetID.ps1 database database_vcn database_subnet"
       register: DatabaseSubnetId

     - include_tasks: 100_CreateVm.yaml
       vars:
        instance_hostname:      "mesrmanp01"
        compartment_id:         "{{ DatabaseCompartmentId.stdout_lines[0] }}"
        subnet_id:              "{{ DatabaseSubnetId.stdout_lines[0] }}"
        shape:                  "VM.Standard2.2"
        availability_domain:    "vSHs:US-ASHBURN-AD-3"
        assign_public_ip:       false
        private_ip:             '10.40.0.3'
        boot_volume_size_in_gbs: 100
        image_id:               "{{ LinuxGoldenImage }}"
#
#     - name: Print Instance source_details
#       debug:
#        msg: "Launch instance completed for MESOEMP01"

# VM MESADMT01
#     - name: Get Compartment Data 
#       command: "pwsh GetActiveChildCompartmentID.ps1 test"
#       register: TestCompartmentId
#
#     - name: Get Subnet Data
#       command: "pwsh GetSubnetID.ps1 test test_vcn test_subnet"
#       register: TestSubnetId
#
#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "mesadmt01"
#        compartment_id:         "{{ TestCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ TestSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard.E2.2"
#        availability_domain:    "vSHs:US-ASHBURN-AD-1"
#        assign_public_ip:       false
#        private_ip:             '10.40.1.2'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ LinuxGoldenImagev2 }}"
#
# Create VM MESDWCAT01
#     - name: Get Compartment Data
#       command: "pwsh GetActiveChildCompartmentID.ps1 test"
#       register: TestCompartmentId
#
#     - name: Get Subnet Data
#       command: "pwsh GetSubnetID.ps1 test test_vcn test_subnet"
#       register: TestSubnetId
#
#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "mesdwcat01"
#        compartment_id:         "{{ TestCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ TestSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard.E2.2"
#        availability_domain:    "vSHs:US-ASHBURN-AD-1"
#        assign_public_ip:       false
#       private_ip:             '10.40.1.3'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ LinuxGoldenImagev2 }}"
#
#     - name: Print Instance source_details
#       debug:
#       msg: "Launch instance completed for mesdwcat01"

# Create VM MESJSBT01
#     - name: Get Compartment Data
#       command: "pwsh GetActiveChildCompartmentID.ps1 test"
#       register: TestCompartmentId
#
#     - name: Get Subnet Data
#       command: "pwsh GetSubnetID.ps1 test test_vcn test_subnet"
#       register: TestSubnetId
#
#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "mesjsbt01"
#        compartment_id:         "{{ TestCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ TestSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard.E2.2"
#        availability_domain:    "vSHs:US-ASHBURN-AD-1"
#        assign_public_ip:       false
#        private_ip:             '10.40.1.4'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ LinuxGoldenImagev2 }}"
#
#    - name: Print Instance source_details
#      debug:
#       msg: "Launch instance completed for mesjsbt01"

# Create VM MESSSBT01
#     - name: Get Compartment Data
#       command: "pwsh GetActiveChildCompartmentID.ps1 test"
#       register: TestCompartmentId
#
#     - name: Get Subnet Data
#       command: "pwsh GetSubnetID.ps1 test test_vcn test_subnet"
#       register: TestSubnetId
#
#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "messsbt01"
#        compartment_id:         "{{ TestCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ TestSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard.E2.2"
#        availability_domain:    "vSHs:US-ASHBURN-AD-1"
#        assign_public_ip:       false
#        private_ip:             '10.40.1.5'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ LinuxGoldenImagev2 }}"
#
#     - name: Print Instance source_details
#       debug:
#        msg: "Launch instance completed for messsbt01"
#
# Create VM MESSSBT02
#     - name: Get Compartment Data
#       command: "pwsh GetActiveChildCompartmentID.ps1 test"
#       register: TestCompartmentId
#
#     - name: Get Subnet Data
#       command: "pwsh GetSubnetID.ps1 test test_vcn test_subnet"
#       register: TestSubnetId
#
#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "messsbt02"
#        compartment_id:         "{{ TestCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ TestSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard.E2.2"
#        availability_domain:    "vSHs:US-ASHBURN-AD-1"
#        assign_public_ip:       false
#        private_ip:             '10.40.1.8'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ LinuxGoldenImagev2 }}"
#
#     - name: Print Instance source_details
#       debug:
#        msg: "Launch instance completed for messsbt02"
#
# Create VM MESESMP01
#     - name: Get Compartment Data
#       command: "pwsh GetActiveChildCompartmentID.ps1 web"
#       register: WebCompartmentId
#
#     - name: Get Subnet Data
#       command: "pwsh GetSubnetID.ps1 web web_vcn intra_subnet"
#       register: IntraSubnetId
#
#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "mesesmp01"
#        compartment_id:         "{{ WebCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ IntraSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard.E2.1"
#        availability_domain:    "vSHs:US-ASHBURN-AD-2"
#        assign_public_ip:       false
#        private_ip:             '10.40.2.11'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ LinuxGoldenImagev2 }}"
#
#     - name: Print Instance source_details
#       debug:
#       msg: "Launch instance completed for mesesmp01"

# Create VM MESODST01
#     - name: Get Compartment Data
#       command: "pwsh GetActiveChildCompartmentID.ps1 test"
#       register: TestCompartmentId
#
#     - name: Get Subnet Data
#       command: "pwsh GetSubnetID.ps1 test test_vcn test_subnet"
#       register: TestSubnetId
#
#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "mesodst01"
#        compartment_id:         "{{ TestCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ TestSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard.E2.2"
#        availability_domain:    "vSHs:US-ASHBURN-AD-1"
#        assign_public_ip:       false
#        private_ip:             '10.40.1.6'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ LinuxGoldenImage }}"
#
#     - name: Print Instance source_details
#       debug:
#        msg: "Launch instance completed for messsbt01"

# Create VM MESODST02
#     - name: Get Compartment Data
#       command: "pwsh GetActiveChildCompartmentID.ps1 test"
#       register: TestCompartmentId

#     - name: Get Subnet Data
#       command: "pwsh GetSubnetID.ps1 test test_vcn test_subnet"
#       register: TestSubnetId

#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "mesodst02"
#        compartment_id:         "{{ TestCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ TestSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard.E2.2"
#        availability_domain:    "vSHs:US-ASHBURN-AD-1"
#        assign_public_ip:       false
#        private_ip:             '10.40.1.7'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ LinuxGoldenImage }}"

#     - name: Print Instance source_details
#       debug:
#        msg: "Launch instance completed for messsbt01"

# Create VM example
#     - name: Get Compartment Data
#       command: "pwsh GetActiveChildCompartment.ps1 web OCID"
#       register: WebCompartmentId

#     - name: Get Subnet Data
#       command: "pwsh GetSubnet.ps1 web web_vcn intra_subnet OCID"
#       register: WebSubnetId

#     - include_tasks: 100_CreateVm.yaml
#       vars:
#        instance_hostname:      "mesapxp01"
#        compartment_id:         "{{ WebCompartmentId.stdout_lines[0] }}"
#        subnet_id:              "{{ WebSubnetId.stdout_lines[0] }}"
#        shape:                  "VM.Standard2.2"
#        availability_domain:    "vSHs:US-ASHBURN-AD-2"
#        assign_public_ip:       false
#        private_ip:             '10.40.2.15'
#        boot_volume_size_in_gbs: 100
#        image_id:               "{{ W2019_GoldenImage }}"

#     - name: Print Instance source_details
#       debug:
#        msg: "Launch instance completed for messsbt01"

