---

# Copyright 2019 – 2020 David Kent Consulting, Inc.
# All Rights Reserved.
# 
# NOTICE:  All information contained herein is, and remains
# the property of David Kent Consulting, Inc.; David Kent Cloud Solutions, Inc.;
# and its affiliates (The Company). The intellectual and technical concepts contained
# herein are proprietary to The Company and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from The Company.
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

- name: Creates Local Peering Gateways and sets up VCN peering
  gather_facts: no
  hosts: localhost
  vars:
    # start with a few global vars, this is a necessary evil of using YAML
    library_path:           "/Users/henrywojteczko/Documents/GitHub/DKC/OCI/master/dev/"
    parent_compartment:     "admin_comp"

    # The code will first create all routes from lists. 

    automation_routing_objects:
      - rt_obj:
          compartment:          "auto_comp"
          vcn_name:             "auto_vcn"
          router_name:          "auto_rtb"
          lpg_name:             "auto_to_bas_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.1.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Bastion network'"
      - rt_obj:
          compartment:          "auto_comp"
          vcn_name:             "auto_vcn"
          router_name:          "auto_rtb"
          lpg_name:             "auto_to_dbs_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.2.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the database network'"
      - rt_obj:
          compartment:          "auto_comp"
          vcn_name:             "auto_vcn"
          router_name:          "auto_rtb"
          lpg_name:             "auto_to_dmz_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.3.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the DMZ network'"
      - rt_obj:
          compartment:          "auto_comp"
          vcn_name:             "auto_vcn"
          router_name:          "auto_rtb"
          lpg_name:             "auto_to_tst_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.4.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the test network'"
      - rt_obj:
          compartment:          "auto_comp"
          vcn_name:             "auto_vcn"
          router_name:          "auto_rtb"
          lpg_name:             "auto_to_vpn0_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.8.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the VPN0 network'"
      - rt_obj:
          compartment:          "auto_comp"
          vcn_name:             "auto_vcn"
          router_name:          "auto_rtb"
          lpg_name:             "auto_to_web_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.6.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the WEB network'"

    bastion_routing_objects:
      - rt_obj:
          compartment:          "bas_comp"
          vcn_name:             "bas_vcn"
          router_name:          "bas_rtb"
          lpg_name:             "bas_to_auto_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.0.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Automation network'"
      - rt_obj:
          compartment:          "bas_comp"
          vcn_name:             "bas_vcn"
          router_name:          "bas_rtb"
          lpg_name:             "bas_to_dbs_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.2.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Database network'"
      - rt_obj:
          compartment:          "bas_comp"
          vcn_name:             "bas_vcn"
          router_name:          "bas_rtb"
          lpg_name:             "bas_to_dmz_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.3.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the DMZ network'"
      - rt_obj:
          compartment:          "bas_comp"
          vcn_name:             "bas_vcn"
          router_name:          "bas_rtb"
          lpg_name:             "bas_to_tst_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.4.0/23"
          region:               "us-ashburn-1"
          description:          "'Route to the Test network'"
      - rt_obj:
          compartment:          "bas_comp"
          vcn_name:             "bas_vcn"
          router_name:          "bas_rtb"
          lpg_name:             "bas_to_vpn0_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.8.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the primary VPN network'"
      - rt_obj:
          compartment:          "bas_comp"
          vcn_name:             "bas_vcn"
          router_name:          "bas_rtb"
          lpg_name:             "bas_to_web_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.6.0/23"
          region:               "us-ashburn-1"
          description:          "'Route to the Web network'"

    database_routing_objects:
      - rt_obj:
          compartment:          "dbs_comp"
          vcn_name:             "dbs_vcn"
          router_name:          "dbs_rtb"
          lpg_name:             "dbs_to_auto_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.0.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Automation network'"
      - rt_obj:
          compartment:          "dbs_comp"
          vcn_name:             "dbs_vcn"
          router_name:          "dbs_rtb"
          lpg_name:             "dbs_to_bas_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.1.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Bastion network'"
      - rt_obj:
          compartment:          "dbs_comp"
          vcn_name:             "dbs_vcn"
          router_name:          "dbs_rtb"
          lpg_name:             "dbs_to_dmz_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.3.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the DMZ network'"
      - rt_obj:
          compartment:          "dbs_comp"
          vcn_name:             "dbs_vcn"
          router_name:          "dbs_rtb"
          lpg_name:             "dbs_to_tst_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.4.0/23"
          region:               "us-ashburn-1"
          description:          "'Route to the Test network'"
      - rt_obj:
          compartment:          "dbs_comp"
          vcn_name:             "dbs_vcn"
          router_name:          "dbs_rtb"
          lpg_name:             "dbs_to_vpn0_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.8.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the primary VPN network'"
      - rt_obj:
          compartment:          "dbs_comp"
          vcn_name:             "dbs_vcn"
          router_name:          "dbs_rtb"
          lpg_name:             "dbs_to_web_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.6.0/23"
          region:               "us-ashburn-1"
          description:          "'Route to the Web network'"
    
    dmz_routing_objects:
      - rt_obj:
          compartment:          "dmz_comp"
          vcn_name:             "dmz_vcn"
          router_name:          "dmz_rtb"
          lpg_name:             "dmz_to_auto_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.0.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Automation network'"
      - rt_obj:
          compartment:          "dmz_comp"
          vcn_name:             "dmz_vcn"
          router_name:          "dmz_rtb"
          lpg_name:             "dmz_to_bas_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.1.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Bastion network'"
      - rt_obj:
          compartment:          "dmz_comp"
          vcn_name:             "dmz_vcn"
          router_name:          "dmz_rtb"
          lpg_name:             "dmz_to_dbs_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.2.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Database network'"
      - rt_obj:
          compartment:          "dmz_comp"
          vcn_name:             "dmz_vcn"
          router_name:          "dmz_rtb"
          lpg_name:             "dmz_to_tst_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.2.0/23"
          region:               "us-ashburn-1"
          description:          "'Route to the Test network'"
      - rt_obj:
          compartment:          "dmz_comp"
          vcn_name:             "dmz_vcn"
          router_name:          "dmz_rtb"
          lpg_name:             "dmz_to_vpn0_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.8.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the primary VPN network'"
      - rt_obj:
          compartment:          "dmz_comp"
          vcn_name:             "dmz_vcn"
          router_name:          "dmz_rtb"
          lpg_name:             "dmz_to_web_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.6.0/23"
          region:               "us-ashburn-1"
          description:          "'Route to the Web network'"

    tst_routing_objects:
      - rt_obj:
          compartment:          "tst_comp"
          vcn_name:             "tst_vcn"
          router_name:          "tst_rtb"
          lpg_name:             "tst_to_auto_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.0.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Automation network'"
      - rt_obj:
          compartment:          "tst_comp"
          vcn_name:             "tst_vcn"
          router_name:          "tst_rtb"
          lpg_name:             "tst_to_bas_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.1.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Bastion network'"
      - rt_obj:
          compartment:          "tst_comp"
          vcn_name:             "tst_vcn"
          router_name:          "tst_rtb"
          lpg_name:             "tst_to_dbs_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.2.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the Database network'"
      - rt_obj:
          compartment:          "tst_comp"
          vcn_name:             "tst_vcn"
          router_name:          "tst_rtb"
          lpg_name:             "tst_to_vpn0_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.8.0/24"
          region:               "us-ashburn-1"
          description:          "'Route to the primary VPN network'"
      - rt_obj:
          compartment:          "tst_comp"
          vcn_name:             "tst_vcn"
          router_name:          "tst_rtb"
          lpg_name:             "tst_to_web_lpg"
          destination_type:     "CIDR_BLOCK"
          destination:          "10.1.6.0/23"
          region:               "us-ashburn-1"
          description:          "'Route to the Web network'"

  tasks:
####################################################################
###           automation compartment network config              ###
####################################################################
  - include_tasks:    010_create_route.yaml
    vars:
    loop: "{{automation_routing_objects}}"

####################################################################
###           bastion compartment network config                 ###
####################################################################
  - include_tasks:    010_create_route.yaml
    vars:
    loop: "{{bastion_routing_objects}}"

####################################################################
###           database compartment network config                ###
####################################################################
  - include_tasks:    010_create_route.yaml
    vars:
    loop: "{{database_routing_objects}}"

####################################################################
###           DMZ compartment network config                     ###
####################################################################
  - include_tasks:    010_create_route.yaml
    vars:
    loop: "{{dmz_routing_objects}}"

####################################################################
###           TST compartment network config                     ###
####################################################################
  - include_tasks:    010_create_route.yaml
    vars:
    loop: "{{tst_routing_objects}}"

####################################################################
###           VPN compartment network config                     ###
####################################################################
#   - include_tasks:    010_create_route.yaml
#     vars:
#     loop: "{{vpn_routing_objects}}"