---

# Copyright 2019 – 2020 David Kent Consulting, Inc.
# All Rights Reserved.
# 
# NOTICE:  All information contained herein is, and remains
# the property of David Kent Consulting, Inc.; David Kent Cloud Solutions, Inc.;
# and its affiliates (The Company). The intellectual and technical concepts contained
# herein are proprietary to The Company and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from The Company.
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

- name: Create parent compartment MESSIAH and its children for the tenancy
  gather_facts: no
  hosts: localhost
  vars:
    # All vars required to create the compartment hierarchy
     compartment_id:            "ocid1.tenancy.oc1..aaaaaaaadr6zwiuddr3etsgyfnldeaxzqfrd7zij33yizbhfk3b5x6uw54sq"       # tenancy is obtained from the root compartment
     parent:                    "MESSIAH"
     Pdescription:              "This is the parent compartment for Messiah College's Banner cloud tenancy"
     AutomationCompartment:     "automation"
     AutomationCompartmentDesc: "The automation compartment will hold all cloud objects that manage automation, such as the ANSIBLE DevOps VM"
     BastionCompartment:        "bastion"
     BastionCompartmentDesc:    "The bastion compartment will hold all cloud objects that provide remote RDS and SSH access to tenancy VMs and DBaaS systems"
     DatabaseCompartment:       "database"
     DatabaseCompartmentDesc:   "The database compartment will hold all database and related objects"
     DatabaseDrCompartment:     "DatabaseDr"
     DatabaseDrCompartmentDesc: "The DR Recovery Database Compartment"
     TestCompartment:           "test"
     TestCompartmentDesc:       "The test compartment will hold all cloud VM resources for the test mid & web tiers"
     VpnDrCompartment:          "VPNDR"
     VpnDrCompartmentDesc:      "Compartment for DR VPN"
     WebCompartment:            "web"
     WebCompartmentDesc:        "The web compartment will hold all production VM resources as well as the DMZ and WAF resources"



  tasks:
     - name: Create the parent compartment MESSIAH
       oci_compartment:
         parent_compartment_id: "{{ compartment_id }}"
         name:                  "{{ parent }}"
         description:           "{{ Pdescription }}"
       register:                MESSHIAH_Compartment


     - name: Print result
       debug:
        msg: "{{ MESSHIAH_Compartment }}"

     - name: Create the Automation compartment
       oci_compartment:
         parent_compartment_id:  "{{ MESSHIAH_Compartment.compartment.id }}"
         name:                   "{{ AutomationCompartment }}"
         description:            "{{ AutomationCompartmentDesc }}"
       register: automation_Compartment

     - name: Print result
       debug:
        msg: "{{ automation_Compartment }}"

     - name: Create the Bastion compartment
       oci_compartment:
         parent_compartment_id:  "{{ MESSHIAH_Compartment.compartment.id }}"
         name:                   "{{ BastionCompartment }}"
         description:            "{{ BastionCompartmentDesc }}"
       register: bastion_Compartment

     - name: Print result
       debug:
        msg: "{{ bastion_Compartment }}"

     - name: Create the Database compartment
       oci_compartment:
         parent_compartment_id:  "{{ MESSHIAH_Compartment.compartment.id }}"
         name:                   "{{ DatabaseCompartment }}"
         description:            "{{ DatabaseCompartmentDesc }}"
       register: test_Compartment

     - name: Create the Test compartment
       oci_compartment:
         parent_compartment_id:  "{{ MESSHIAH_Compartment.compartment.id }}"
         name:                   "{{ TestCompartment }}"
         description:            "{{ TestCompartmentDesc }}"
       register: test_Compartment

     - name: Print result
       debug:
        msg: "{{ test_Compartment }}"

     - name: Create the web compartment
       oci_compartment:
         parent_compartment_id:  "{{ MESSHIAH_Compartment.compartment.id }}"
         name:                   "{{ WebCompartment }}"
         description:            "{{ WebCompartmentDesc }}"
       register: web_Compartment

     - name: Print result
       debug:
        msg: "{{ web_Compartment }}"

     - name: Create the Database DR compartment
       oci_compartment:
         parent_compartment_id:  "{{ MESSHIAH_Compartment.compartment.id }}"
         name:                   "{{ DatabaseDrCompartment }}"
         description:            "{{ DatabaseDrCompartmentDesc }}"
       register: DatabaseDr_Compartment

     - name: Print result
       debug:
        msg: "{{ DatabaseDr_Compartment }}"

     - name: Create the vpn DR compartment
       oci_compartment:
         parent_compartment_id:  "{{ compartment_id }}"
         name:                   "{{ VpnDrCompartment }}"
         description:            "{{ VpnDrCompartmentDesc }}"
       register: VpnDr_Compartment

     - name: Print result
       debug:
        msg: "{{ VpnDr_Compartment }}"