---

# Copyright 2019 – 2020 David Kent Consulting, Inc.
# All Rights Reserved.
# 
# NOTICE:  All information contained herein is, and remains
# the property of David Kent Consulting, Inc.; David Kent Cloud Solutions, Inc.;
# and its affiliates (The Company). The intellectual and technical concepts contained
# herein are proprietary to The Company and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from The Company.
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

- name: Creates Subnets within the ERP tenant
  gather_facts: no
  hosts: localhost
  vars:
    Automation:
      compartment:  "auto_comp"
      vcn_name:  "auto_vcn"
      sub_name: "auto_sub"
      sub_dns:  "autosub"
      sub_cidr: "172.16.4.0/24"
      prohibit_public_ip_on_vnic: no
      region: "US-ASHBURN-1"
    Bastion:
      compartment:  "bas_comp"
      vcn_name:  "bas_vcn"
      sub_name: "bas_sub"
      sub_dns:  "bassub"
      sub_cidr: "172.16.5.0/24"
      prohibit_public_ip_on_vnic: no
      region: "US-ASHBURN-1"
    Database:
      compartment:  "dbs_comp"
      vcn_name:  "dbs_vcn"
      sub_name: "dbs_sub"
      sub_dns:  "dbssub"
      sub_cidr: "172.16.0.0/24"
      prohibit_public_ip_on_vnic: yes
      region: "US-ASHBURN-1"
    Dmz:
      compartment: "dmz_comp"
      vcn_name: "dmz_vcn"
      vcn_dnsName: "dmzvcn"
      sub_name: "dmz_sub"
      sub_dns: "dmzsub"
      sub_cidr: "172.16.6.0/24"
      prohibit_public_ip_on_vnic: no
      region: "US-ASHBURN-1"
    Dr:
      compartment:  "dr_comp"
      vcn_name:  "dr_vcn"
      sub_name: "dr_sub01"
      sub_dns:  "drsub01"
      sub_cidr: "172.16.128.0/24"
      prohibit_public_ip_on_vnic: yes
      region: "US-PHOENIX-1" 
    Test00:
      compartment:  "tst_comp"
      vcn_name:  "tst_vcn"
      sub_name: "tst_sub"
      sub_dns:  "tstsub"
      sub_cidr: "172.16.1.0/25"
      prohibit_public_ip_on_vnic: no
      region: "US-ASHBURN-1"
    Test01:
      compartment:  "tst_comp"
      vcn_name:  "tst_vcn"
      sub_name: "tst_podsub"
      sub_dns:  "tstpodsub"
      sub_cidr: "172.16.1.128/25"
      prohibit_public_ip_on_vnic: yes
      region: "US-ASHBURN-1"
    Vpn:
      compartment:  "vpn_comp"
      vcn_name:  "vpn_vcn"
      sub_name: "vpn_sub"
      sub_dns:  "vpnsub"
      sub_cidr: "172.16.7.0/24"
      prohibit_public_ip_on_vnic: yes
      region: "US-ASHBURN-1"
    VpnDr:
      compartment:  "vpn_comp"
      vcn_name:  "vpndr_vcn"
      sub_name: "vpndr_sub"
      sub_dns:  "vpndrsub"
      sub_cidr: "172.16.8.0/24"
      prohibit_public_ip_on_vnic: yes
      region: "US-PHOENIX-1" 
    Web00:
      compartment:  "web_comp"
      vcn_name:  "web_vcn"
      sub_name: "web_sub"
      sub_dns:  "websub"
      sub_cidr: "172.16.2.0/24"
      prohibit_public_ip_on_vnic: no
      region: "US-ASHBURN-1"
    Web01:
      compartment:  "web_comp"
      vcn_name:  "web_vcn"
      sub_name: "web_podsub"
      sub_dns:  "webpodsub"
      sub_cidr: "172.16.3.0/24"
      prohibit_public_ip_on_vnic: yes
      region: "US-ASHBURN-1"

  tasks:

# Now we pass vars to 011_CreateSubnet.yaml to create each subnet if not present
  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ Automation }}"

  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ Bastion }}"

  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ Database }}"

  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ Dmz }}"

  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ Dr }}"

  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ Test00 }}"
  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ Test01 }}"

  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ Vpn }}"

  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ VpnDr }}"
      
  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ Web00 }}"

  - include_tasks: 011_CreateSubnet.yaml
    vars:
      VcnProperties:  "{{ Web01 }}"
  