---
# Copyright 2019 – 2020 David Kent Consulting, Inc.
# All Rights Reserved.
# 
# NOTICE:  All information contained herein is, and remains
# the property of David Kent Consulting, Inc.; David Kent Cloud Solutions, Inc.;
# and its affiliates (The Company). The intellectual and technical concepts contained
# herein are proprietary to The Company and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from The Company.
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

- name: Create block volumes and attach to VM instances in the tenancy
  gather_facts: no
  hosts: localhost
  vars:
    NWMSUBASP01:
      instance_hostname:            "nwmsubasp01"
      availability_domain:          "sIah:US-ASHBURN-AD-3"
      DataVolSize:                  500
    NWMSURMANP01:
      instance_hostname:            "nwmsurmanp01"
      availability_domain:          "sIah:US-ASHBURN-AD-1"
      DataVolSize:                  50
    NWMSUJSUBT01:
      instance_hostname:            "nwmsujsubp01"
      availability_domain:          "sIah:US-ASHBURN-AD-2"
      DataVolSize:                  100

# Compartment and VCN data
    Automation:
      compartment:                  "auto_comp"
      vcn_name:                     "auto_vcn"
      subnet_name:                  "auto_sub"
      region:                       "US-ASHBURN-1"
    Bastion:
      compartment:                  "bas_comp"
      vcn_name:                     "bas_vcn"
      subnet_name:                  "bas_sub"
      region:                       "US-ASHBURN-1"
    Database:
      compartment:                  "dbs_comp"
      vcn_name:                     "dbs_vcn"
      subnet_name:                  "dbs_sub"
      region:                       "US-ASHBURN-1"
    Test:
      compartment:                  "tst_comp"
      vcn_name:                     "tst_vcn"
      subnet_name:                  "tst_sub"
      region:                       "US-ASHBURN-1"
    Web:
      compartment:                  "web_comp"
      vcn_name:                     "web_vcn"
      subnet_name:                  "web_sub"
      region:                       "US-ASHBURN-1"

# image data
    images:
      ole_golden_image_id:          "ocid1.image.oc1.iad.aaaaaaaa246eitegc3lelewfckeh2gcdmqsnydw7vwax2e4dk43vnpvxf6oa"
      windows_golden_image:         "ocid1.image.oc1.iad.aaaaaaaagy3diwbmerf2f2yhlp2mmycv2d6dz2536af34mb7626cscvuqdvq"

    # All vars required to create this VM
    # This VM to be created in the bastion compartment. It will have a publically visible IP address.
    # The security list is to be used to restrict access to the VM as needed, such as blocking internet
    # access.

  tasks:
    - include_tasks: 101_CreateAndAttachBlockVolume.yaml
      vars:
        VM:                     "{{ NWMSUBASP01 }}"
        VcnProperties:          "{{ Bastion }}"

    - include_tasks: 101_CreateAndAttachBlockVolume.yaml
      vars:
        VM:                     "{{ NWMSURMANP01 }}"
        VcnProperties:          "{{ Database }}"
        
    - include_tasks: 101_CreateAndAttachBlockVolume.yaml
      vars:
        VM:                     "{{ NWMSUJSUBT01 }}"
        VcnProperties:          "{{ Database }}"