---
# Copyright 2019 – 2020 David Kent Consulting, Inc.
# All Rights Reserved.
# 
# NOTICE:  All information contained herein is, and remains
# the property of David Kent Consulting, Inc.; David Kent Cloud Solutions, Inc.;
# and its affiliates (The Company). The intellectual and technical concepts contained
# herein are proprietary to The Company and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from The Company.
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

- name: Create File Systems in OCI Tenant
  gather_facts: no
  hosts: localhost
  vars:
    python_path:                    "/home/opc/bin/python"
    DKCFST01:
      availability_domain:          "clNq:US-ASHBURN-AD-2"
      display_name:                 "DKCFST01"
      mt_display_name:              "DKCFST01_MT"
      hostname_label:               "DKCFST01"
      ip_address:                   "172.16.0.100"
    DKCFSP01:
      availability_domain:          "clNq:US-ASHBURN-AD-3"
      display_name:                 "DKCFSP01"
      mt_display_name:              "DKCFSP01_MT"
      hostname_label:               "DKCFSP01"
      ip_address:                   "172.16.0.101"
    DKCFSP02:
      availability_domain:          "clNq:PHX-AD-3"
      display_name:                 "DKCFSP02"
      mt_display_name:              "DKCFSP02_MT"
      hostname_label:               "DKCFSP02"
      ip_address:                   "172.16.128.100"

      

# Compartment and VCN data
    Database:
      compartment:                  "dbs_comp"
      vcn_name:                     "dbs_vcn"
      subnet_name:                  "dbs_sub"
      region:                       "US-ASHBURN-1"
    DR:
      compartment:                  "dr_comp"
      vcn_name:                     "dr_vcn"
      subnet_name:                  "dr_sub01"
      region:                       "US-PHOENIX-1"

    # All vars required to create this VM
    # This VM to be created in the bastion compartment. It will have a publically visible IP address.
    # The security list is to be used to restrict access to the VM as needed, such as blocking internet
    # access.

  tasks:
    - include_tasks: 300_CreateFileSystem.yaml
      vars:
        FileSystem:                       "{{ DKCFST01 }}"
        VcnProperties:                    "{{ Database }}"

    - include_tasks: 300_CreateFileSystem.yaml
      vars:
        FileSystem:                       "{{ DKCFSP01 }}"
        VcnProperties:                    "{{ Database }}"

    - include_tasks: 300_CreateFileSystem.yaml
      vars:
        FileSystem:                       "{{ DKCFSP02 }}"
        VcnProperties:                    "{{ DR }}"