---
# Copyright 2019 – 2020 David Kent Consulting, Inc.
# All Rights Reserved.
# 
# NOTICE:  All information contained herein is, and remains
# the property of David Kent Consulting, Inc.; David Kent Cloud Solutions, Inc.;
# and its affiliates (The Company). The intellectual and technical concepts contained
# herein are proprietary to The Company and may be covered by U.S. and Foreign Patents,
# patents in process, and are protected by trade secret or copyright law.
# Dissemination of this information or reproduction of this material
# is strictly forbidden unless prior written permission is obtained
# from The Company.
#
# This file is subject to the terms and conditions defined in
# file 'LICENSE.txt', which is part of this source code package.

- name: Create Kubernetes Cluster in OCI Tenant
  gather_facts: no
  hosts: localhost
  vars:
    python_path:                    "/home/opc/bin/python"
    DKCKBC01:
      kubernetes_version:           "v1.15.7"
      name:                         "DKCKBC01"
      options:
        add_ons:
          is_kubernetes_dashboard_enabled: yes
          is_tiller_enabled: no
        kubernetes_network_config:
          pods_cidr:                "10.96.0.0/16"
          services_cidr:            "10.244.0.0/16"
      wait:                         "no"
    DKCKBC02:
      kubernetes_version:           "v1.15.7"
      name:                         "DKCKBC02"
      options:
        add_ons:
          is_kubernetes_dashboard_enabled: yes
          is_tiller_enabled: no
        kubernetes_network_config:
          pods_cidr:                "10.96.0.0/16"
          services_cidr:            "10.244.0.0/16"
      wait:                         "no"
    DKCKBC03:
      kubernetes_version:           "v1.15.7"
      name:                         "DKCKBC03"
      options:
        add_ons:
          is_kubernetes_dashboard_enabled: yes
          is_tiller_enabled: no
        kubernetes_network_config:
          pods_cidr:                "10.96.0.0/16"
          services_cidr:            "10.244.0.0/16"
      wait:                         "no"

# Compartment and VCN data
    DR:
      compartment:                  "dr_comp"
      vcn_name:                     "dr_vcn"
      subnet_name:                  "dr_sub01"
      region:                       "US-PHOENIX-1"
    Test:
      compartment:                  "tst_comp"
      vcn_name:                     "tst_vcn"
      subnet_name:                  "tst_sub"
      region:                       "US-ASHBURN-1"
    Web:
      compartment:                  "web_comp"
      vcn_name:                     "web_vcn"
      subnet_name:                  "web_sub"
      region:                       "US-ASHBURN-1"

    # All vars required to create this VM
    # This VM to be created in the bastion compartment. It will have a publically visible IP address.
    # The security list is to be used to restrict access to the VM as needed, such as blocking internet
    # access.

  tasks:
    - include_tasks: 400_CreateKbCluster.yaml
      vars:
        KbCluster:                        "{{ DKCKBC01 }}"
        VcnProperties:                    "{{ Test }}"

    - include_tasks: 400_CreateKbCluster.yaml
      vars:
        KbCluster:                        "{{ DKCKBC02 }}"
        VcnProperties:                    "{{ Web }}"

    - include_tasks: 400_CreateKbCluster.yaml
      vars:
        KbCluster:                        "{{ DKCKBC03 }}"
        VcnProperties:                    "{{ DR }}"